### ISSUE TITLE
No input in first round gives error

### ISSUE THREAD

**Issue by jeongm** [Bartleby2718/DieOrDare#32]
When no input is given in the first round, program throws error
Error log below. 

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\...\venv\lib\site-packages\keyboard\__init__.py", line 292, in listen
    _os_keyboard.listen(self.direct_callback)
  File "C:\Users\...\venv\lib\site-packages\keyboard\_winkeyboard.py", line 560, in listen
    prepare_intercept(callback)
  File "C:\Users\...\venv\lib\site-packages\keyboard\_winkeyboard.py", line 553, in prepare_intercept
    keyboard_hook = SetWindowsHookEx(WH_KEYBOARD_LL, keyboard_callback, GetModuleHandleW(NULL), NULL)
ctypes.ArgumentError: argument 3: <class 'OverflowError'>: int too long to convert
```

Also when the game is over, program prints message for debugging? 
` {'player_red': <__main__.Player object at 0x0000022C06246BA8>, 'player_black': <__main__.Player object at 0x0000022C0623F400>, 'over': True, 'time_created': 1538937401.2499528, 'time_ended': 1538937520.6470702, 'winner': <__main__.Player object at 0x0000022C0623F400>, 'loser': <__main__.Player object at 0x0000022C06246BA8>, 'result': 'Finished', 'duel_index': 3, 'duel_ongoing': None, 'red_pile': [], 'black_pile': [], 'num_human_players': 2}`

**Comment by jeongm** [comment]
Environment 
Windows 10 Version 1803 (OS Build 17134.285)
PyCharm Professional 2018.2.3
Python 3.7

keyboard | 0.13.2 | 
--- | --- | 
pip | 18.0 |
pynput | 1.4 | 
setuptools | 39.0.1 | 
six | 1.11.0 | 



On the last message print, I guess for final release you would not need it, but for now it is fine.
To be honest I did not understand the rules when I first ran the script, so I was not sure what to do.
So when the message said `What will you two do?` I just did not do anything and it threw the above error. Yet the program continues to run no matter what.

**Comment by Bartleby2718** [comment]
Based on [this StackOverflow comment](https://stackoverflow.com/questions/44163105/python-3-5-1-amd64-ctypes-argumenterror-argument-1-class-overflowerror#comment75389333_44163105), this seems to be a bug in the keyboard package. I'll have to find the simplest example that causes this error before I report it, provided it hasn't been reported yet.

**Comment by Bartleby2718** [comment]
Well, [the same issue](https://github.com/boppreh/keyboard/issues/186) was reported three months ago but hasn't been fixed yet.
